-- 0001_schema.sql
-- E-commerce analytics schema. Small, denormalized enough for LLM-friendly
-- text-to-SQL but rich enough that questions like "top 5 products by revenue
-- last month" or "share of orders by status" have a real answer.

set search_path = public, pg_catalog;

create table if not exists public.users (
  id          bigint primary key generated by default as identity,
  email       text   not null unique,
  signup_date date   not null default current_date
);

create table if not exists public.products (
  id         bigint        primary key generated by default as identity,
  name       text          not null,
  category   text          not null,
  unit_price numeric(10,2) not null check (unit_price >= 0)
);

create table if not exists public.orders (
  id         bigint      primary key generated by default as identity,
  user_id    bigint      not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  status     text        not null default 'pending'
              check (status in ('pending', 'paid', 'shipped', 'cancelled'))
);

create table if not exists public.order_items (
  id         bigint        primary key generated by default as identity,
  order_id   bigint        not null references public.orders(id) on delete cascade,
  product_id bigint        not null references public.products(id),
  quantity   integer       not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0)
);

create index if not exists idx_orders_user_id        on public.orders(user_id);
create index if not exists idx_orders_created_at     on public.orders(created_at);
create index if not exists idx_order_items_order_id  on public.order_items(order_id);
create index if not exists idx_order_items_product_id on public.order_items(product_id);

-- Optional analytics table. Seeded if seed script encounters it; harmless if
-- empty. Lets the LLM tackle "how many users signed up in the last week" via
-- events.name = 'signup' as an alternative to users.signup_date.
create table if not exists public.events (
  id         bigint      primary key generated by default as identity,
  user_id    bigint      references public.users(id) on delete set null,
  name       text        not null,
  created_at timestamptz not null default now(),
  properties jsonb       not null default '{}'::jsonb
);

create index if not exists idx_events_user_id    on public.events(user_id);
create index if not exists idx_events_created_at on public.events(created_at);
create index if not exists idx_events_name       on public.events(name);
